title:
    - case_name: 配置-规则配置-价格配置
testcase:
    - element_info: //span[text()='配置']
      find_type: xpath
      operate_type: click
      step: 点击"配置"
    - element_info: mCSB_1_container
      find_type: id
      operate_type: forSliding
      step: 向上滑动
    - element_info: //a[@href='/authorized/merchant/setting/exchangeConfig']
      find_type: xpath
      operate_type: click
      step: 点击"规则配置"
      frame: MainBoard
    - element_info: //span[text()='新增']
      find_type: xpath
      operate_type: click
      step: 点击新增
    - element_info: //*[@id="name"]
      find_type: xpath
      operate_type: send_date_now
      text: AutoUI
      step: 输入价格规则名称
    - element_info: //*[@id="discount"]
      find_type: xpath
      operate_type: send_keys
      text: 0.8
      step: 输入折扣
    - element_info: //*[@id="factor"]
      find_type: xpath
      operate_type: send_keys
      text: 258
      step: 设置常数
    - element_info: //*[@id="rate"]
      find_type: xpath
      operate_type: send_keys
      text: 369
      step: 输入汇率
    - element_info: //*[@id="freight"]
      find_type: xpath
      operate_type: send_keys
      text: 147
      step: 输入运费
    - element_info: //span[text()='保存']
      find_type: xpath
      operate_type: click
      step: 点击保存
    - element_info: //button[text()='OK']
      find_type: xpath
      operate_type: click
      step: 点击OK
    - element_info: /html/body/div[1]/div[2]/div[1]/table/tbody/tr[4]/td[5]/a[1]
      find_type: xpath
      operate_type: click
      step: 点击修改
    - element_info: //*[@id="name"]
      find_type: xpath
      operate_type: send_date_now
      text: AutoUI
      step: 输入新价格规则名称
    - element_info: //*[@id="discount"]
      find_type: xpath
      operate_type: send_keys
      text: 0.7
      step: 输入新折扣
    - element_info: //*[@id="factor"]
      find_type: xpath
      operate_type: send_keys
      text: 255
      step: 设置新常数
    - element_info: //*[@id="rate"]
      find_type: xpath
      operate_type: send_keys
      text: 366
      step: 输入新汇率
    - element_info: //*[@id="freight"]
      find_type: xpath
      operate_type: send_keys
      text: 144
      step: 输入新运费
    - element_info: //span[text()='保存']
      find_type: xpath
      operate_type: click
      step: 点击保存
    - element_info: //button[text()='OK']
      find_type: xpath
      operate_type: click
      step: 点击OK
    - element_info: //a[text()[normalize-space()='已禁用']]
      find_type: xpath
      operate_type: click
      step: 点击启用
    - element_info: //button[text()='确认']
      find_type: xpath
      operate_type: click
      step: 点击确认
    - element_info: (//font[text()='已启用'])[3]
      find_type: xpath
      operate_type: click
      step: 点击禁用
    - element_info: //button[text()='确认']
      find_type: xpath
      operate_type: click
      step: 点击确认
    - element_info: /html/body/div[1]/div[2]/div[1]/table/tbody/tr[4]/td[5]/a[2]
      find_type: xpath
      operate_type: click
      step: 点击删除
    - element_info: //button[text()='确认']
      find_type: xpath
      operate_type: click
      step: 确认删除


check:
    - element_info: //div[text()='删除成功']
      find_type: xpath
      step: 检查是否删除成功