title:
    - case_name: 配置-规则配置-产品标题生成配置
testcase:
    - element_info: //span[text()='配置']
      find_type: xpath
      operate_type: click
      step: 点击"配置"
    - element_info: mCSB_1_container
      find_type: id
      operate_type: forSliding
      step: 向上滑动
    - element_info: //a[@href='/authorized/merchant/setting/exchangeConfig']
      find_type: xpath
      operate_type: click
      step: 点击"规则配置"
      frame: MainBoard
    - element_info: //span[text()='产品字段默认值配置']
      find_type: xpath
      operate_type: click
      step: 点击产品字段默认值配置
    - element_info: //span[text()='新增']
      find_type: xpath
      operate_type: click
      step: 点击新增
    - element_info: //*[@id="name"]
      find_type: xpath
      operate_type: send_date_now
      text: AutoUI
      step: 输入产品字段默认值配置名称
    - element_info: //label[text()='平台选择']
      find_type: xpath
      operate_type: click
      step: 点击使图标加载
    - element_info: //label[text()[normalize-space()='京东']]
      find_type: xpath
      operate_type: click
      step: 选择京东平台
    - element_info: /html/body/div[1]/form/ul/li[3]/div[1]/div/div/div[3]/ul/li[2]/ul/li[1]/a
      find_type: xpath
      operate_type: click
      step: 选择第一个行业
    - element_info: /html/body/div[1]/form/ul/li[4]/div[1]/label[1]/input
      find_type: xpath
      operate_type: click
      step: 选择第一个字段
    - element_info: //*[@id="1FieldValue"]
      find_type: xpath
      operate_type: send_date_now
      text: AutoUI
      step: 输入第一个字段值
    - element_info: //button[text()='保存']
      find_type: xpath
      operate_type: click
      step: 点击保存
    - element_info: (//font[text()='已启用'])[7]
      find_type: xpath
      operate_type: click
      step: 切换为禁用
    - element_info: //button[text()='确认']
      find_type: xpath
      operate_type: click
      step: 点击确认
    - element_info: //a[text()[normalize-space()='已禁用']]
      find_type: xpath
      operate_type: click
      step: 切换为启用
    - element_info: //button[text()='确认']
      find_type: xpath
      operate_type: click
      step: 点击确认
    - element_info: /html/body/div[1]/table/tbody/tr[7]/td[6]/a[1]
      find_type: xpath
      operate_type: click
      step: 点击修改
    - element_info: /html/body/div[1]/form/ul/li[4]/div[1]/label[2]/input
      find_type: xpath
      operate_type: click
      step: 选择第二个字段
    - element_info: //*[@id="2FieldValue"]
      find_type: xpath
      operate_type: send_date_now
      text: AutoUI
      step: 输入第二个字段值
    - element_info: //button[text()='保存']
      find_type: xpath
      operate_type: click
      step: 点击保存
    - element_info: /html/body/div[1]/table/tbody/tr[7]/td[6]/a[2]
      find_type: xpath
      operate_type: click
      step: 点击删除
    - element_info: //button[text()='确认']
      find_type: xpath
      operate_type: click
      step: 确认删除


check:
    - element_info: //button[text()='OK']
      find_type: xpath
      step: 检查是否删除成功